const mongoose = require("mongoose");

const applicationSchema = new mongoose.Schema(
  {
    jobId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "JobPost",
      required: true,
    },
    candidateId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    status: {
      type: String,
      enum: [
        "applied",
        "shortlisted",
        "ai_screening",
        "interview_scheduled",
        "interview_done",
        "rejected",
        "accepted",
        "offered",
      ],
      default: "applied",
    },

    aiFitScore: { type: Number }, // Resume Matcher AI output

    interview: {
      scheduledAt: Date,
      zoomLink: String,
      feedback: String,
      feedbackSummary: String, // Generated by Interview Summary Generator
      interviewerId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    },

    offerLetter: {
      url: String,
      accepted: Boolean,
      respondedAt: Date,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

const ApplicationModel = mongoose.model("Application", applicationSchema);

module.exports = { ApplicationModel };
